apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  #Terminal command to encode data
  #echo -n 'plain_text_here' | base64
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=